<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php 
$helper = $this->helper('Alrais\VehicleFilter\Helper\Data');
$selectedVehicle = json_decode($helper->getVehicle());
if($selectedVehicle){
    $disbled = $helper->isVehicleFitsProduct($selectedVehicle->vehicle_id, $_product->getId()) ? "" : "disabled" ;
}else{
    $disbled = "disabled";
}
if($_product->getUniversalProduct()){
    $disbled = "";
}
?>

<?php if ($_product->isSaleable()): ?>
    <?php if ($block->shouldRenderQuantity()): ?>
    <div class="qty">    
        <input type="number"
                        <?= $disbled ?>
                        name="qty"
                        id="qty"
                        value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                        title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                        class="input-text"
                        data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
    </div>
    <?php endif; ?>
    <button type="submit"
            <?= $disbled ?>
            title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
            class="action tocart cart_btn"
            id="product-addtocart-button">
        <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
    </button>
    <?= $block->getChildHtml('', true) ?>
    <script>
        require(["jquery"], function($){
            $("#product-addtocart-button").on("click",function(){
                $('html, body').animate({scrollTop:0},500);
            });
        });
    </script>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
