<?php
$_objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$_config = $_objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
$_disableDefaultMenu = $_config->getValue('codazon_megamenu/general/disable_default_menu', 'store');
?>
<button class="menu_container_btn"><i class="fa fa-bars"></i></button>
<div id="desk_menu-container" class="hidden-xs pos_static">
<div class="close_btn_container"><button class="close_btn_container"><i class="fa fa-close"></i></button></div>
<?php if($_disableDefaultMenu): ?>
	<?php $_usedMegamenu = $_config->getValue('codazon_megamenu/general/used_megamenu', 'store'); ?>
	<nav class="cdz-navigation" data-action="navigation">
	<?php echo $_objectManager->get('Codazon\MegaMenu\Block\Widget\Megamenu')->setMenu($_usedMegamenu)->toHtml(); ?>
	</nav>
<?php else: ?>
	<?php echo $_objectManager->get('Magento\Theme\Block\Html\Topmenu')->setTemplate('Magento_Theme::html/topmenu.phtml')->toHtml(); ?>
<?php endif ?>
</div>
<div class="offermnu"><a href="<?= $this->getUrl('deals')?>"><?= __('SPECIAL OFFERS') ?>!</a></div>
<script>
    require(["jquery"],function($){
        $(".menu_container_btn").on("click", function(){
            $("#desk_menu-container").css("display", "block");
        });
        $(".close_btn_container").on("click", function(){
            $("#desk_menu-container").css("display", "none");
        });
    });
    </script>
