<section class="deal_list" id="clearance-items">
    <div class="loading-mask" data-role="loader">
        <div class="loader">
            <img alt="<?= __('Loading...')?>" src="">
            <p><?= __('Please wait...')?></p>
        </div>
    </div>
</section>
<script type="text/x-magento-init">
    {
    "[data-role=tocart-form], .form.map.checkout": {
    "catalogAddToCart": {}
    }
    }
</script>