<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
?>
<section class="subpaghead">
			<div class="container">
				<ul class="bradcrumb_li" data-mage-init='<?= /* @escapeNotVerified */ $viewModel->getJsonConfiguration() ?>'>
					
				</ul>
			</div>
		</section>