<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$productHelper = $this->helper('Alrais\ProductDetails\Helper\Data');
$quickviewHelper = $this->helper('Alrais\Quickview\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ul class="productlisting">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $product): ?>
                <li class="product_list_item">
                    <div class="badges_blk">
                        <?php if ($product->getOfferLabel()):?> 
                            <span class="blue"><?= __($product->getAttributeText('offer_label'))?></span>
                        <?php endif?>
                        <?php if ($product->getTypeId() == 'bundle'):?> 
                            <span class="blue"><?= __('Bundle')?></span>
                        <?php endif?>
                        <?php if ($product->getCustomAttribute('strikethrough_price')):?> 
                            <span class="red"><?= __('DEAL')?></span>
                        <?php endif?>
                        <?php 
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $localDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
                        $newsFromDate = $product->getNewsFromDate();
                        $newsToDate = $product->getNewsToDate();
                        if (!$newsFromDate && !$newsToDate) {
                            $showNewLabel = false;
                        }else{
                            if($localDate->isScopeDateInInterval(
                                $product->getStore(),
                                $newsFromDate,
                                $newsToDate
                            )){
                                $showNewLabel = true;
                            }else{
                                $showNewLabel = false;
                            }
                        }
                        ?>
                        <?php if ($showNewLabel):?> 
                            <span class="green"><?= __('NEW')?></span>
                        <?php endif?>
                    </div>
                    <div class="imageholder_pr">
                        <a href="<?= $product->getProductUrl() ?>">
                            <img loading="lazy" src="<?= $productHelper->getImage($product) ?>" />
                        </a>
                    </div>
                    <div class="buttons">
                        <?= $productHelper->getAddToCart($product)?>
                        <?= $quickviewHelper->getQuickView($product); ?>
                    </div>
                    <div class="product_nme">
                        <a href="<?= $product->getProductUrl() ?>">
                            <?= $product->getName() ?>
                        </a>
                    </div>
                    <div class="prices test-list b">
                        <?php if ($productHelper->getDiscountPercentage($product) > 0): ?>
                            <!-- <span class="actaual_price base"><?= $productHelper->getOriginalPrice($product); ?></span> &nbsp; -->
                        <?php endif ?>

                        <?php if ($product->getSpecialPrice()): ?>
                            <!-- <span class="actaual_price if_special"><?= $productHelper->getOriginalPrice($product); ?></span> &nbsp; -->
                        <?php endif ?>

                        <?php if ($product->getCustomAttribute('bundle_original_price')): ?>
                            <!-- <span class="actaual_price bundle"><?php echo 
                                $this->helper('Magento\framework\pricing\helper\data')->currency($product->getCustomAttribute('bundle_original_price')->getValue(),true,false); 
                            ?></span> -->
                        <?php endif ?>

                        <?php if ($product->getCustomAttribute('strikethrough_price')): ?>
                            <span class="actaual_price simple"><?php echo 
                                $this->helper('Magento\framework\pricing\helper\data')->currency($product->getCustomAttribute('strikethrough_price')->getValue(),true,false); 
                            ?></span>
                        <?php endif ?>

                        <span class="special_price"><?= $productHelper->getFinalPrice($product); ?></span>

                        <div class="stockstaus">
                            <?php if ($product->isAvailable()): ?>
                                <i class="fa fa-check-square-o"></i><span><?= /* @escapeNotVerified */ __('In stock') ?></span>
                            <?php else: ?>
                                <i class="fa fa-square-o"></i><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                            <?php endif; ?>
                        </div>
                        
                            
                    </div>
                    
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
