<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<!-- <?php //if ($block->isProductVisibleInSiteVisibility()): ?>
    <a class="edit_delate"
       href="<? //= /* @escapeNotVerified */ $block->getConfigureUrl() ?>"
       title="<? //= $block->escapeHtml(__('Edit item parameters')) ?>">
        <i class="fa fa-edit"></i>
   </a>
<?php //endif ?> -->
