<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>
<a href="#"
   title="<?= $block->escapeHtml(__('Remove item')) ?>"
   class="edit_delate"
   data-post='<?= /* @escapeNotVerified */ $block->getDeletePostJson() ?>'>
   <i class="fa fa-trash"></i>
</a>
