<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>
    
<?php
$productHelper = $this->helper('Alrais\ProductDetails\Helper\Data');
$quickviewHelper = $this->helper('Alrais\Quickview\Helper\Data');
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}
?>

<?php if ($exist):?>
    <?php $items = $productHelper->loadProducts($items);?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php else: ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= /* @escapeNotVerified */ $class ?>">
    <?php endif; ?>
    <h1 class="releted_upsell"><?= $title ?></h1>
    <div class="product-listing bottom" id="list-<?= $type?>">
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($items as $product): ?>
            <div class="item">
                <div class="slide-div">
                    <div class="badges_blk">
                        <?php if ($product->getOfferLabel()):?> 
                            <span class="blue"><?= __($product->getAttributeText('offer_label'))?></span>
                        <?php endif?>
                        <?php if ($product->getTypeId() == 'bundle'):?> 
                            <span class="blue"><?= __('Bundle')?></span>
                        <?php endif?>
                        <?php if ($product->getSpecialPrice()):?> 
                            <span class="red"><?= __('DEAL')?></span>
                        <?php endif?>
                        <?php 
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $localDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
                        $newsFromDate = $product->getNewsFromDate();
                        $newsToDate = $product->getNewsToDate();
                        if (!$newsFromDate && !$newsToDate) {
                            $showNewLabel = false;
                        }else{
                            if($localDate->isScopeDateInInterval(
                                $product->getStore(),
                                $newsFromDate,
                                $newsToDate
                            )){
                                $showNewLabel = true;
                            }else{
                                $showNewLabel = false;
                            }
                        }
                        ?>
                        <?php if ($showNewLabel):?> 
                            <span class="green"><?= __('NEW')?></span>
                        <?php endif?>
                    </div>
                    <div class="imageholder_pr">
                        <a href="<?= $product->productUrl ?>">
                            <img src="<?= $product->imageUrl ?>" />
                        </a>
                    </div>
                    <div class="buttons">
                        <?= $product->addtocart ?>
                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                            <?= $product->wishlist; ?>
                        <?php endif; ?>
                        <?= $quickviewHelper->getQuickView($product); ?>
                    </div>
                    <div class="product_nme">
                        <a href="<?= $product->productUrl ?>">
                            <?= $product->name ?>
                        </a>
                    </div>
                    <div class="prices test-items a">
                        <?php if ($product->discountPercentage > 0): ?>
                            <!-- <span class="actaual_price"><?= $product->originalPrice; ?></span> &nbsp; -->
                        <?php endif ?>
                        
                        <?php if ($product->getCustomAttribute('bundle_original_price')): ?>
                            <span class="actaual_price"><?php echo $product->getCustomAttribute('bundle_original_price')->getValue(); ?></span>
                        <?php endif ?>

                        <?php if ($product->getSpecialPrice()): ?>
                            <span class="actaual_price"><?= $productHelper->getOriginalPrice($product); ?></span> &nbsp;
                        <?php endif ?>

                        <span class="special_price"><?= $product->finalPrice; ?></span>

                        <div class="stockstaus">
                            <?php if ($product->isAvailable()): ?>
                                <i class="fa fa-check-square-o"></i><span><?= /* @escapeNotVerified */ __('In stock') ?></span>
                            <?php else: ?>
                                <i class="fa fa-square-o"></i><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                            <?php endif; ?>
                        </div>
                        
                    </div>

                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <script src="<?= $this->getViewFileUrl('Alrais_MainSlider::js/jquery.bxslider.js')?>"></script>
    <script>
        require(['jquery'], function ($) {
            $(document).ready(function() {
                $('#list-<?= $type ?>').bxSlider({
                    minSlides: 1,
                    maxSlides: 5,
                    slideWidth: 243,
                    slideMargin: 10,
                    responsive: true,
                    infiniteLoop: false

                });
            });
        });

    </script>
<?php endif;?>
