<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<div class="prdct-options float">
    <?php $_filters = $block->getActiveFilters() ?>
    <?php if (!empty($_filters)): ?>
        <ul class="option-list">
            <?php foreach ($_filters as $_filter): ?>
                <li>
                    <?php echo $block->escapeHtml(__($_filter->getName())); ?>
                    <?php /* @escapeNotVerified */ echo $block->stripTags($_filter->getLabel()) ?>
                    <?php
                    $clearLinkUrl = $_filter->getClearLinkUrl();
                    $currentFilterName = $block->escapeHtml(__($_filter->getName())) . "-" . $block->stripTags($_filter->getLabel());
                    if ($clearLinkUrl):
                        ?>
                        <a class="action previous" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                           title="<?php /* @escapeNotVerified */ echo __('Previous') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Previous') ?></span>
                        </a>
                        <a class="action remove"
                           title="<?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                           href="<?php /* @escapeNotVerified */ echo $clearLinkUrl ?>">
                            <span><?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                        </a>
                    <?php else: ?>
                        <span class="close-btn">
                            <a class="action remove" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                               title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Remove')) . " " . $currentFilterName; ?>">
                                <span>X</span>
                            </a>
                        </span>

                    <?php endif; ?>


                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>
